import React, { useState, useEffect } from 'react';
import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import api from '../utils/api';
import './CompletedOrders.css';
import ProgressNavBar from "../Components/ProgressNavBar";

const ProductionReportPDF = ({ order }) => (
  <Document>
    <Page style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.header}>Production Completion Report</Text>
        <Text style={styles.subHeader}>Order #{order.orderId}</Text>
        
        <View style={styles.divider}></View>
        
        <View style={styles.summarySection}>
          <Text style={styles.summaryTitle}>Order Summary</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>Total Production Time</Text>
              <Text style={styles.summaryValue}>{order.totalEstimatedTime} hours</Text>
            </View>
            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>Priority Level</Text>
              <Text style={styles.summaryValue}>{order.priorityLevel}</Text>
            </View>
            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>Risk Level</Text>
              <Text style={styles.summaryValue}>{order.riskLevel}</Text>
            </View>
            <View style={styles.summaryItem}>
              <Text style={styles.summaryLabel}>Completion Date</Text>
              <Text style={styles.summaryValue}>{new Date().toLocaleDateString()}</Text>
            </View>
          </View>
        </View>
        
        <View style={styles.tasksSection}>
          <Text style={styles.sectionTitle}>Production Tasks</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={styles.tableHeaderCell}>Task</Text>
              <Text style={styles.tableHeaderCell}>Status</Text>
              <Text style={styles.tableHeaderCell}>Time (hrs)</Text>
              <Text style={styles.tableHeaderCell}>Due Date</Text>
            </View>
            
            {order.tasks?.map((task, index) => (
              <View style={styles.tableRow} key={index}>
                <Text style={styles.tableCell}>{task.taskName}</Text>
                <Text style={[styles.tableCell, styles[`status-${task.status.toLowerCase().replace(' ', '-')}`]]}>
                  {task.status}
                </Text>
                <Text style={styles.tableCell}>{task.estimatedTime}</Text>
                <Text style={styles.tableCell}>
                  {task.dueDate ? new Date(task.dueDate).toLocaleDateString() : 'N/A'}
                </Text>
              </View>
            ))}
          </View>
        </View>
        
        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by Luxury Furniture Manufacturing System</Text>
        </View>
      </View>
    </Page>
  </Document>
);

const styles = StyleSheet.create({
  page: { 
    padding: 40,
    fontFamily: 'Helvetica'
  },
  header: { 
    fontSize: 24, 
    marginBottom: 5, 
    fontWeight: 'bold',
    color: '#4e342e',
    fontFamily: 'Times-Bold'
  },
  subHeader: { 
    fontSize: 16, 
    marginBottom: 20,
    color: '#8d6e63'
  },
  divider: {
    height: 1,
    backgroundColor: '#c8a97e',
    marginBottom: 20
  },
  summarySection: {
    marginBottom: 25
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4e342e',
    marginBottom: 10
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between'
  },
  summaryItem: {
    width: '48%',
    marginBottom: 10
  },
  summaryLabel: {
    fontSize: 12,
    color: '#8d6e63'
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4e342e'
  },
  tasksSection: {
    marginBottom: 20
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4e342e',
    marginBottom: 10
  },
  table: {
    display: 'table',
    width: '100%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#e0d6c2'
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f5f3f0',
    borderBottomWidth: 1,
    borderBottomColor: '#e0d6c2'
  },
  tableHeaderCell: {
    width: '25%',
    padding: 8,
    fontWeight: 'bold',
    color: '#5d4037',
    fontSize: 12
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f0e6d2'
  },
  tableCell: {
    width: '25%',
    padding: 8,
    color: '#5d4037',
    fontSize: 12
  },
  'status-pending': {
    backgroundColor: '#fff3e0',
    color: '#e65100'
  },
  'status-in-progress': {
    backgroundColor: '#e3f2fd',
    color: '#1565c0'
  },
  'status-completed': {
    backgroundColor: '#e8f5e9',
    color: '#2e7d32'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center'
  },
  footerText: {
    fontSize: 10,
    color: '#8d6e63'
  }
});

const CompletedOrders = () => {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedOrder, setSelectedOrder] = useState(null);

  useEffect(() => {
    const fetchOrders = async () => {
      try {
        setLoading(true);
        setError(null);
        const response = await api.get('/tasks/orders');
        setOrders(response.data.filter(order => order.progress === 100));
      } catch (error) {
        console.error("Error fetching completed orders:", error);
        setError("Failed to load completed orders");
      } finally {
        setLoading(false);
      }
    };
    fetchOrders();
  }, []);

  if (loading) return (
    <div className="loading-container">
      <div className="loading-spinner"></div>
      Loading completed orders...
    </div>
  );
  
  if (error) return (
    <div className="error-container">
      <span className="error-icon">⚠️</span>
      {error}
    </div>
  );

  return (
    <>
      <ProgressNavBar />
      <div className="completed-orders-container">
        <div className="orders-header">
          <h1 className="orders-title">Completed Production</h1>
          <p className="orders-subtitle">Finished manufacturing orders</p>
          <div className="stats-summary">
            <div className="stat-item">
              <span className="stat-value">{orders.length}</span>
              <span className="stat-label">Completed Orders</span>
            </div>
          </div>
        </div>

        {selectedOrder ? (
          <div className="report-view">
            <div className="report-header">
              <h2 className="report-title">
                <span className="back-button" onClick={() => setSelectedOrder(null)}>
                  &larr;
                </span>
                Order #{selectedOrder.orderId} Report
              </h2>
              
              <div className="summary-cards">
                <div className="summary-card">
                  <span className="summary-label">Total Time</span>
                  <span className="summary-value">
                    {selectedOrder.totalEstimatedTime} hours
                  </span>
                </div>
                <div className="summary-card">
                  <span className="summary-label">Priority</span>
                  <span className={`priority-badge ${selectedOrder.priorityLevel.toLowerCase()}`}>
                    {selectedOrder.priorityLevel}
                  </span>
                </div>
                <div className="summary-card">
                  <span className="summary-label">Risk Level</span>
                  <span className="summary-value">
                    {selectedOrder.riskLevel}
                  </span>
                </div>
              </div>
            </div>

            <div className="tasks-table-container">
              <table className="tasks-table">
                <thead>
                  <tr>
                    <th>Task Name</th>
                    <th>Status</th>
                    <th>Time (hrs)</th>
                    <th>Due Date</th>
                  </tr>
                </thead>
                <tbody>
                  {selectedOrder.tasks?.map((task, index) => (
                    <tr key={index}>
                      <td>{task.taskName}</td>
                      <td>
                        <span className={`status-badge ${task.status.toLowerCase().replace(' ', '-')}`}>
                          {task.status}
                        </span>
                      </td>
                      <td>{task.estimatedTime}</td>
                      <td>
                        {task.dueDate ? new Date(task.dueDate).toLocaleDateString() : 'N/A'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="report-actions">
              <PDFDownloadLink
                document={<ProductionReportPDF order={selectedOrder} />}
                fileName={`luxury_furniture_report_${selectedOrder.orderId}.pdf`}
                className="pdf-button"
              >
                {({ loading }) => (
                  loading ? 'Preparing Report...' : 'Download PDF Report'
                )}
              </PDFDownloadLink>
            </div>
          </div>
        ) : (
          <div className="orders-grid-container">
            {orders.length === 0 ? (
              <div className="empty-state">
                <div className="empty-icon">🎉</div>
                <h3 className="empty-title">No Completed Orders</h3>
                <p className="empty-text">All completed orders will appear here</p>
              </div>
            ) : (
              <div className="orders-grid">
                {orders.map(order => (
                  <div key={order._id} className="order-card">
                    <div className="card-header">
                      <span className="order-id">Order #{order.orderId}</span>
                      <span className={`priority-badge ${order.priorityLevel.toLowerCase()}`}>
                        {order.priorityLevel}
                      </span>
                    </div>
                    <div className="card-body">
                      <div className="meta-item">
                        <span className="meta-label">Production Time:</span>
                        <span className="meta-value">{order.totalEstimatedTime} hours</span>
                      </div>
                      <div className="meta-item">
                        <span className="meta-label">Risk Level:</span>
                        <span className="meta-value">{order.riskLevel}</span>
                      </div>
                    </div>
                    <div className="card-footer">
                      <button
                        className="view-button"
                        onClick={() => setSelectedOrder(order)}
                      >
                        View Full Report
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </>
  );
};

export default CompletedOrders;